config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"

  get '/ranking', to: 'ranking#index'
  get '/ranking/live', to: 'ranking#live'

  get '/sounds', to: 'sounds#index'

  resources :guests, only: [:index, :create, :new, :destroy]

  resources :guests do
    get :points, on: :collection

    member do
      post :add_points
    end
  end

  resources :messages, only: [:index, :create]
  resources :messages do
    get :live, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/guest.rb
# frozen_string_literal: true

class Guest < ApplicationRecord
  has_many :point_events
  scope :ranked, -> { order(points: :desc) }

  def add_points(number)
    if self.points + number < 0
      number = -self.points
    end

    self.points += number

    point_events.create!(points: number)
  end
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  def as_json
    { id: id, name: name, message: message, time: created_at.in_time_zone('CET').strftime("%H:%M") }
  end
end

app/models/point_event.rb
# frozen_string_literal: true

class PointEvent < ApplicationRecord
  belongs_to :guest

  def as_json
    { id: id, guest: guest.id, points: points, name: guest.name }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  protect_from_forgery with: :null_session, only: :add_points

  def index
    @guests = Guest.all
  end

  def points
    @guests = Guest.ranked
  end

  def add_points
    @guest = Guest.find(params[:id])
    @guest.add_points(points_params[:points].to_i)
    @guest.save!
  end

  def new
    @guest = Guest.new
  end

  def create
    @guest = Guest.new guest_params
    if @guest.save
      redirect_to guests_path
    else
      render :new
    end
  end

  def destroy
    @guest = Guest.find(params[:id])
    begin
      @guest.destroy
    rescue ActiveRecord::DeleteRestrictionError => e
      @guest.errors.add(:base, e)
    ensure
      redirect_to guests_path
    end
  end

  private

  def guest_params
    params.require(:guest).permit(:name, :points)
  end

  def points_params
    params.permit(:points)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    # Sort!
    @messages = Message.all.order(created_at: :desc)
  end

  def create
    @message = Message.new message_params
    @message.save!
  end

  def live
    render json: last_message
  end

  private

  def last_message
    Message.last&.as_json
  end

  def message_params
    params.require(:message).permit(:name, :message)
  end
end

app/controllers/ranking_controller.rb
class RankingController < ApplicationController
  layout "game", :only => [ :index ]

  def index
    @guests = Guest.ranked
    @last_change_id = PointEvent.last&.id || 0
  end

  def live
    render json: ranking_details
  end

  private

  def ranking_details
    {
      order: Guest.ranked.map { |guest| { id: guest.id, points: guest.points } },
      last_change: PointEvent.last.as_json
    }
  end
end

app/controllers/sounds_controller.rb
class SoundsController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/guests/index.html.haml
.title GuEsts

.list-guests.col
  - @guests.each do |guest|
    .row.guest
      .name= guest.name
      .del=link_to "X", guest_path(guest), method: :delete, data: { turbo_method: :delete }

.col.sticky
  .white-bg.row
    %a{ href: points_guests_path }= "Scores"
  .blue-bg.row
    %a{ href: new_guest_path }= "new"

app/views/guests/new.html.haml
.title new

.add-guest
  = simple_form_for @guest, class: 'col' do |f|
    = f.input :name
    .row
      Points?
      = f.number_field :points, input_html: { class: 'form-control-lg' }, grid_wrapper_html: { class: 'col-sm-6 '}

    = f.button :submit, class: 'button white-bg' do
      Save Person
    = link_to('Cancel', guests_path, class: 'button cancel blue-bg')

app/views/guests/points.html.haml
.title points

.list-guests.col
  - @guests.each do |guest|
    .col.guest{ data: { controller: 'scoring', 'score-guest-id' => guest.id }, id: guest.name }
      .row.guest
        .name= guest.name
        .points{ data: {scoring: { target: 'points'}, points: guest.points} }= guest.points
      .row.point-add
        .button.add.dark-bg{data: {scoring: {target: 'add' }}} +
        .button.subtract.white-bg{data: {scoring: { target: 'subtract' }}} -
        .button.submit.dark-bg{data: {scoring: { target: 'submit' }, postto: add_points_guest_path(guest.id)}} submit

=link_to guests_path do
  .blue-bg.row.sticky
    back

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Katja & Mattia</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
     <meta name="description" content="30 September 2023">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/game.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Katjamattia</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="purple-bg">
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/index.html.haml
-# controller that fetches updates
.messages-container{data: {controller: 'messages', endpoint: live_messages_path, lastmessage: @messages.first&.id || 0}}
  .list-messages.col{data: {messages: {target: 'list'}}}
    - @messages.each do |message|
      .col.message-container
        .row.name
          = message.name
          .heart{id: message.id, data: {action: 'click->messages#switchHeart', marked: 0}}
            .closed.hidden
              :plain
                <svg id="Layer_2" data-name="Layer 2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 22.34 18.29">
                  <g id="Layer_2-2" data-name="Layer 2">
                    <path d="m20.34,1.19c-2.2-1.82-5.49-1.49-7.51.53l-1.66,1.66-1.66-1.66C7.49-.3,4.21-.63,2,1.19-.53,3.28-.66,7.04,1.6,9.3l8.59,8.59c.54.54,1.41.54,1.95,0l6.77-6.77,1.82-1.82c2.26-2.26,2.13-6.02-.4-8.1Z"/>
                  </g>
                </svg>
            .open
              :plain
                <svg id="Layer_2" data-name="Layer 2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 22.34 18.29">
                  <g id="Layer_2-2" data-name="Layer 2">
                    <path d="m5.38,1c1.27,0,2.52.52,3.43,1.43l1.66,1.66.71.71.71-.71,1.66-1.66c.91-.91,2.16-1.43,3.43-1.43,1.03,0,1.97.33,2.74.97.99.82,1.57,1.97,1.63,3.25.06,1.26-.42,2.49-1.31,3.38l-1.82,1.82-6.77,6.77c-.1.1-.21.11-.27.11s-.17-.01-.27-.11L2.31,8.59c-.89-.89-1.37-2.12-1.31-3.38.06-1.27.64-2.43,1.63-3.25.76-.63,1.71-.97,2.74-.97m0-1c-1.2,0-2.4.38-3.38,1.19C-.53,3.28-.66,7.04,1.6,9.3l8.59,8.59c.27.27.62.4.98.4s.71-.13.98-.4l6.77-6.77,1.82-1.82c2.26-2.26,2.13-6.02-.4-8.1C19.35.39,18.16,0,16.96,0,15.46,0,13.95.6,12.82,1.72l-1.66,1.66-1.66-1.66c-1.12-1.12-2.63-1.72-4.13-1.72h0Z"/>
                  </g>
                </svg>
        .row.message= message.message
        .row.time= message.created_at.in_time_zone('CET').strftime("%H:%M")

  .add-message.white-bg.col.sticky{data: {messages: {target: 'footer'}}}
    .blocky.dark-bg
    .blocky.keep-right.dark-bg
    .form.col
      = simple_form_for :message, remote: true, html: {'data-messages-target': 'form', 'data-action': "turbo:submit-end->messages#handleSubmit"} do |f|
        = f.input :name, label: false, placeholder: "Name...", input_html: { class: 'namebox white-bg', data: {'messages-target': 'name'} }, grid_wrapper_html: { class: 'col-sm-6 '}
        = f.input :message, as: :text, label:false, placeholder: "Message...", input_html: { class: 'textbox white-bg' , data: {'messages-target': 'mess'}}, grid_wrapper_html: { class: 'col-sm-6 '}
        .row
          = link_to root_path, class: 'back' do
            .inner
              :plain
                <svg id="Layer_2" data-name="Layer 2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 11.8 23.6">
                  <defs>
                    <style>
                      .cls-1 {
                        fill: #1e1e1e;
                        stroke-width: 0px;
                      }
                    </style>
                  </defs>
                  <g id="Layer_1-2" data-name="Layer 1">
                    <polygon class="cls-1" points="11.8 0 0 11.8 11.8 23.6 11.8 0"/>
                  </g>
                </svg>
          = f.button :submit, "Send", class: 'button-send blue-bg'

app/views/ranking/index.html.haml
.ranking{ data: {controller: 'game', endpoint: ranking_live_path, lastchange: @last_change_id}}
  .scrollable
    .title GAMe
    .listings{data: {game: {target: 'listings'}}}
      - @guests.each_with_index do |guest, index|
        .guest.col{id: guest.id}
          .top.row
            .index= "# #{index + 1}"
            .change.hidden
            .points= guest.points
          .bottom.row
            .name= guest.name
            .points
  .row.wtf.blue-bg.sticky{data: {game: {target: 'footer'}}}
    = link_to root_path, class: 'back-button white-bg' do
      .border-left-down
        .inner
          :plain
            <svg id="Layer_2" data-name="Layer 2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 11.8 23.6">
              <defs>
                <style>
                  .cls-1 {
                    fill: #1e1e1e;
                    stroke-width: 0px;
                  }
                </style>
              </defs>
              <g id="Layer_1-2" data-name="Layer 1">
                <polygon class="cls-1" points="11.8 0 0 11.8 11.8 23.6 11.8 0"/>
              </g>
            </svg>
    .question{data: {action: 'click->game#wtf'}} WTF?

  .added-points.overlay.blue-bg.hidden{ data: {game: {target: 'add' }}}
    .points{ data: {game: {target: 'addPoints' }}}
    .icon.star
      :plain
        <svg id="Layer_2" data-name="Layer 2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 228.64 226.35">
          <defs>
            <style>
              .star-cls {
                fill: #ff8849;
                stroke-width: 0px;
              }
            </style>
          </defs>
          <g id="Layer_1-2" data-name="Layer 1">
            <polygon class="star-cls" points="228.64 113.17 148.29 118.11 224.03 145.37 145.57 127.42 210.48 175.02 140.27 135.64 189.2 199.56 132.85 142.07 161.84 217.17 124.01 146.12 130.54 226.35 114.32 147.49 98.1 226.35 104.63 146.12 66.8 217.17 95.79 142.07 39.44 199.56 88.37 135.64 18.16 175.01 83.07 127.42 4.61 145.37 80.35 118.11 0 113.17 80.35 108.24 4.61 80.97 83.07 98.93 18.16 51.33 88.37 90.71 39.44 26.78 95.79 84.27 66.8 9.18 104.63 80.23 98.1 0 114.32 78.85 130.55 0 124.01 80.23 161.84 9.18 132.85 84.27 189.2 26.79 140.27 90.71 210.48 51.33 145.57 98.93 224.03 80.98 148.29 108.24 228.64 113.17"/>
          </g>
        </svg>
    .col.sticky.purple-bg
      .name{ data: {game: {target: 'addName' }}}
  .removed-points.overlay.green-bg.hidden{ data: {game: {target: 'removed' }}}
    .points{ data: {game: {target: 'removedPoints' }}}
    .icon.face
      :plain
        <svg id="Layer_2" data-name="Layer 2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 123.25 90.66">
          <defs>
            <style>
              .cls-face {
                fill: #648dff;
                stroke-width: 0px;
              }
            </style>
          </defs>
          <g id="Layer_1-2" data-name="Layer 1">
            <path class="cls-face" d="m116.61,90.66c0-32.2-26.1-58.31-58.31-58.31S0,58.46,0,90.66h116.61Z"/>
            <circle class="cls-face" cx="13.82" cy="13.82" r="13.82"/>
            <circle class="cls-face" cx="109.43" cy="15.71" r="13.82"/>
          </g>
        </svg>
    .col.sticky.purple-bg
      .name{ data: {game: {target: 'removedName' }}}

  .wtf-desc.hidden.overlay.blue-bg{ data: {game: {target: 'wtf' }}}
    .col
      .exit{data: {action: 'click->game#wtfGone'}} X
      earn points and win a fantastic prize

app/views/sounds/index.html.haml
.title SOUND

.sounds-boxes.col{data: {controller: 'sounds'}}
  .row.boxes
    .box.blue-bg{data: {action: "click->sounds#play"}}= audio_tag "BIRD.mp3"
    .box.purple-bg{data: {action: "click->sounds#play"}}= audio_tag "BRITNEY.mp3"
    .box.orange-bg{data: {action: "click->sounds#play"}}= audio_tag "DODOS.mp3"
  .row.boxes
    .box.orange-bg{data: {action: "click->sounds#play"}}= audio_tag "FANTOZZI.mp3"
    .box.white-bg{data: {action: "click->sounds#play"}}= audio_tag "GIMBO.mp3"
    .box.purple-bg{data: {action: "click->sounds#play"}}= audio_tag "XP2.mp3"
  .row.boxes
    .box.blue-bg{data: {action: "click->sounds#play"}}= audio_tag "POM POM.mp3"
    .box.blue-bg{data: {action: "click->sounds#play"}}= audio_tag "RUSSIA.mp3"
    .box.white-bg{data: {action: "click->sounds#play"}}= audio_tag "WAKE AND BAKE.mp3"
  .row.boxes
    .box.purple-bg{data: {action: "click->sounds#play"}}= audio_tag "XP1.mp3"
    .box.orange-bg{data: {action: "click->sounds#play"}}= audio_tag "MEGLIO MALE.mp3"
    = link_to root_path, class: 'box white-bg back' do
      :plain
        <svg id="Layer_2" data-name="Layer 2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 11.8 23.6">
          <defs>
          <style>
            .cls-1 {
            fill: #1e1e1e;
            stroke-width: 0px;
            }
          </style>
          </defs>
          <g id="Layer_1-2" data-name="Layer 1">
          <polygon class="cls-1" points="11.8 0 0 11.8 11.8 23.6 11.8 0"/>
          </g>
        </svg>

app/views/welcome/_coming_soon.html.haml
.coming-soon{data: {controller: 'coming', action: 'click->coming#destroy'}}
  .ball.initial.white-bg{data: {coming: {target: 'ball'}}}
  .content{data: {coming: {target: 'content'}}}
    .logo
    .slogan
      Viva GLi
      sposi!
    .description
      .line 2
      .line SEPTEMBER
      .line 2023

app/views/welcome/index.html.haml
.logo{data: {controller: 'hello'}}

.menu
  = link_to ranking_path do
    .bar.purple-bg
      GAMe
  = link_to messages_path do
    .bar.orange-bg
      MessaGe
  = link_to sounds_path do
    .bar.green-bg
      Sound

.names

= render partial: 'coming_soon'